INCLUDE(../odin.cmake/odin.cmake)

SET(PROJECT_NAME valheim.vulkan)

FIND_PACKAGE(volk CONFIG REQUIRED)

ODIN_SETUP_LIBRARY(${PROJECT_NAME})

ODIN_LINK_CORE(${PROJECT_NAME})
ODIN_LINK_CGLTF(${PROJECT_NAME})
ODIN_LINK_CGLM(${PROJECT_NAME})
ODIN_LINK_SPRIV_REFLECT(${PROJECT_NAME})
ODIN_LINK_GLFW(${PROJECT_NAME})
ODIN_LINK_ASSIMP(${PROJECT_NAME})
ODIN_LINK_MESHOPTIMIZER(${PROJECT_NAME})
ODIN_LINK_CIMGUI(${PROJECT_NAME})

TARGET_LINK_LIBRARIES(
	${PROJECT_NAME}
	PUBLIC
	volk::volk
	volk::volk_headers
)
