CMAKE_MINIMUM_REQUIRED(VERSION 3.30)

SET(PROJECT_NAME valheim)
SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ../)
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ../)
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ../)

PROJECT(${PROJECT_NAME} C ASM_NASM)

ADD_SUBDIRECTORY(valheim.core)
ADD_SUBDIRECTORY(valheim.vulkan)
ADD_SUBDIRECTORY(valheim.app)

