FUNCTION(ODIN_INCLUDE_SOURCES PROJECT_TARGET)
    SET(${PROJECT_TARGET}_SOURCES "")

    FILE(GLOB_RECURSE SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/src/*.c)
    FILE(GLOB_RECURSE HEADERS ${CMAKE_CURRENT_SOURCE_DIR}/src/*.h)

    IF (SOURCES)
        LIST(APPEND ${PROJECT_TARGET}_SOURCES ${SOURCES} ${HEADERS})
    ENDIF ()

    FUNCTION(ODIN_INCLUDE_SOURCES_R DIR)
        FILE(GLOB SUBDIRS ${DIR}/*)

        FOREACH (SUBDIR ${SUBDIRS})
            IF (IS_DIRECTORY ${SUBDIR})
                FILE(GLOB_RECURSE DIR_SOURCES ${SUBDIR}/*.c)

                FOREACH (DIR_SOURCE ${DIR_SOURCES})
                    LIST(APPEND ${PROJECT_TARGET}_SOURCES ${DIR_SOURCES})

                    SET(${PROJECT_TARGET}_SOURCES ${${PROJECT_TARGET}_SOURCES} PARENT_SCOPE)
                ENDFOREACH ()

                ODIN_INCLUDE_SOURCES_R(${SUBDIR})
            ENDIF ()
        ENDFOREACH ()
    ENDFUNCTION()

    ODIN_INCLUDE_SOURCES_R(${CMAKE_CURRENT_SOURCE_DIR})

    SET(${PROJECT_TARGET}_SOURCES ${${PROJECT_TARGET}_SOURCES} PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(ODIN_TARGET_INCLUDE_HEADERS PROJECT_TARGET DIR)
    SET(${PROJECT_TARGET}_HEADERS "")

    FILE(GLOB HEADERS ${CMAKE_CURRENT_SOURCE_DIR}/src/*.h)

    MACRO(ODIN_INCLUDE_HEADERS_R DIR)
        FILE(GLOB SUBDIRS ${DIR}/*)

        FOREACH (SUBDIR ${SUBDIRS})
            IF (IS_DIRECTORY ${SUBDIR})
                FILE(GLOB DIR_HEADERS ${SUBDIR}/*.h)

                IF (DIR_HEADERS)
                    LIST(APPEND ${PROJECT_TARGET}_HEADERS ${SUBDIR})
                ENDIF ()

                ODIN_INCLUDE_HEADERS_R(${SUBDIR})
            ENDIF ()
        ENDFOREACH ()
    ENDMACRO()

    ODIN_INCLUDE_HEADERS_R(${CMAKE_CURRENT_SOURCE_DIR})

    MESSAGE("Including Dirs: ${${PROJECT_TARGET}_HEADERS}")
    TARGET_INCLUDE_DIRECTORIES(${PROJECT_TARGET} PUBLIC ${${PROJECT_TARGET}_HEADERS})
ENDFUNCTION()

FUNCTION(ODIN_SETUP_LIBRARY TARGET)
    PROJECT(${TARGET} C)

    ODIN_INCLUDE_SOURCES(${TARGET})
    ADD_LIBRARY(${TARGET} SHARED ${${TARGET}_SOURCES})
    SET_PROPERTY(TARGET ${TARGET} PROPERTY C_STANDARD 23)

    ODIN_TARGET_INCLUDE_HEADERS(${TARGET} ${CMAKE_CURRENT_SOURCE_DIR})

    TARGET_COMPILE_DEFINITIONS(
        ${TARGET}
        PRIVATE
        ODIN_EXPORT
    )
    #TARGET_COMPILE_OPTIONS(${TARGET} PRIVATE "/std:clatest") 
ENDFUNCTION()

FUNCTION(ODIN_SETUP_EXE TARGET)
    PROJECT(${TARGET} C)

    ODIN_INCLUDE_SOURCES(${TARGET})
    ADD_EXECUTABLE(${TARGET} ${${TARGET}_SOURCES})
    SET_PROPERTY(TARGET ${TARGET} PROPERTY C_STANDARD 23)
    #TARGET_COMPILE_OPTIONS(${TARGET} PRIVATE "/std:clatest") 

    ODIN_TARGET_INCLUDE_HEADERS(${TARGET} ${CMAKE_CURRENT_SOURCE_DIR})
ENDFUNCTION()

FUNCTION(ODIN_LINK_CORE TARGET)
    TARGET_LINK_LIBRARIES(
        ${TARGET}
        PUBLIC
        valheim.core
    )
ENDFUNCTION()

FUNCTION(ODIN_LINK_CGLM TARGET)
	FIND_PACKAGE(cglm CONFIG REQUIRED)

    TARGET_LINK_LIBRARIES(
        ${TARGET}
        PUBLIC
        cglm::cglm
    )
ENDFUNCTION()

FUNCTION(ODIN_LINK_ASSIMP TARGET)
    FIND_PACKAGE(assimp CONFIG REQUIRED)
    TARGET_LINK_LIBRARIES(${TARGET} PUBLIC assimp::assimp)
ENDFUNCTION()

FUNCTION(ODIN_LINK_CGLTF TARGET)
    FIND_PATH(CGLTF_INCLUDE_DIRS "cgltf.h")
    TARGET_INCLUDE_DIRECTORIES(${TARGET} PUBLIC ${CGLTF_INCLUDE_DIRS})
ENDFUNCTION()

FUNCTION(ODIN_LINK_SPRIV_REFLECT TARGET)
    FIND_PACKAGE(unofficial-spirv-reflect CONFIG REQUIRED)
    TARGET_LINK_LIBRARIES(${TARGET} PUBLIC unofficial::spirv-reflect)
ENDFUNCTION()

FUNCTION(ODIN_LINK_GLEW TARGET)
	FIND_PACKAGE(GLEW REQUIRED)
	TARGET_LINK_LIBRARIES(${TARGET} PUBLIC GLEW::GLEW)
ENDFUNCTION()

FUNCTION(ODIN_LINK_GLFW TARGET)
	FIND_PACKAGE(glfw3 REQUIRED)
	TARGET_LINK_LIBRARIES(${TARGET} PUBLIC glfw)
ENDFUNCTION()

FUNCTION(ODIN_LINK_MESHOPTIMIZER TARGET)
    FIND_PACKAGE(meshoptimizer CONFIG REQUIRED)
    TARGET_LINK_LIBRARIES(${TARGET} PUBLIC meshoptimizer::meshoptimizer)
ENDFUNCTION()
